### PR TITLE
feat(iconPack): add new icons pack

### PR DESCRIPTION
**Pull request by Lisandra-dev**
- Boxicons
- RPG awesome

### CODE REVIEW

**Comment by FlorianWoelki** [comment]
Thanks for adding these icon packs.

Just one question: do the icon packs have their custom repository where I can download the zip file for the icon pack? Or do we need to have the zip files in the Iconize repository?

**Comment by Lisandra-dev** [comment]
I created the zip myself because boxicons and rpg awesome doesn't provide release with svg.

I created the boxicons using a custom github actions on my fork: https://github.com/Lisandra-dev/boxicons

And the zip for rpg awesome was created using the rpg awesome raw icon repo : https://github.com/nagoshiashumari/rpg-awesome-raw

For the second I can do the same for boxicons and use the release and we can add the zip directly using the release instead of your repository!

**Comment by FlorianWoelki** [comment]
> I created the zip myself because boxicons and rpg awesome doesn't provide release with svg.
> 
> I created the boxicons using a custom github actions on my fork: https://github.com/Lisandra-dev/boxicons
> 
> And the zip for rpg awesome was created using the rpg awesome raw icon repo : https://github.com/nagoshiashumari/rpg-awesome-raw
> 
> For the second I can do the same for boxicons and use the release and we can add the zip directly using the release instead of your repository!

Yeah, I would prefer using the zip files from the repositories of their GitHub releases.

**Comment by Lisandra-dev** [comment]
I created release from fork of Boxicons and rpg-awesome, deleted the zip & used the links I created from the release

**Comment by FlorianWoelki** [comment]
> I created release from fork of Boxicons and rpg-awesome, deleted the zip & used the links I created from the release

Why don't you just use the direct links of their repositories?

**Comment by Lisandra-dev** [comment]
They have nor : 
- Tags
- Release
- Zip archive

**Comment by FlorianWoelki** [comment]
> They have nor : 
> 
> - Tags
> 
> - Release
> 
> - Zip archive
> 
> 
> 
> 

Got it!

Then we can keep the icon packs in the Iconize repository. Sorry for the confusion :D

**Comment by Lisandra-dev** [comment]
I will re-add them, then!

**Comment by Lisandra-dev** [comment]
Done ✅

**Review by FlorianWoelki — APPROVED** [review]

**Pull request merged**
