### PR TITLE
fix: customRule ignore inheritance

### LINKED ISSUE #225: [BUG]: Conflict between inheritance & custom rules
**Describe the bug**
I have a rule that apply to all markdown files (`.md`). 
If I try to set an inheritance icon:
- First I have duplication with the rule icon and the inherited icon.
- If I reload, I get the ruled icon, not the inherited. 

**To Reproduce**
1. Create a custom "general" rules, for ie `\.md$` files.
2. Inherit an icon on file in a folder
3. See duplication
4. Reload Obsidian
5. See that only the ruled icon is applied

**Expected behavior**
Normally, the inherited icon must be applied, not the ruled ?

**Screenshots**
https://github.com/FlorianWoelki/obsidian-icon-folder/assets/30244939/57d65b12-2d52-4b3a-afdd-890f77a70b08

**Additional context**
I tried custom rules, but because of the order, the `\.md` is applied in last and result in a strange "blink" between the icon

### PR DESCRIPTION
**Pull request by Lisandra-dev**
I hope you don't mind about spamming PR. I love this plugin, and I want to help you to maintain this. Moreover, working on this plugin help me to learn a lot about Typescript and how to work with API in general. Your plugin is very pleasant to work with. You comment a lot and it's pretty useful!

This plugin help me a lot IRL because of ADHD, and it's my favorite 100% so I really want to help you!

So, what I do in this PR is just to fix #225. Pretty simple, in fact. I just added `hasInheritance` and checking it before applying the rule.

### CODE REVIEW

**Comment by FlorianWoelki** [comment]
Don't worry, I am always happy when someone contributes to the plugin! :)

Generally, I've tried to develop the `lib` directory as standalone libraries which can be used by others and throughout the application. Therefore, I am not a big fan of using `inheritance` in the `customRule` library. Wouldn't it be possible to implement this somewhere else?

**Comment by Lisandra-dev** [comment]
I made another implementation for this fix!

**Comment by FlorianWoelki** [comment]
Feel free to checkout [this PR](https://github.com/FlorianWoelki/obsidian-iconize/pull/235) which is a simpler implementation of your fix. Could you please verify if this PR is working for you?

**Comment by FlorianWoelki** [comment]
Closed due to #235

**Pull request closed without merging**
