### PR TITLE
fix: set default emoji style to 'native'

### PR DESCRIPTION
**Pull request by quanru**
before fix: image

after fix: 
image

### CODE REVIEW

**Comment by FlorianWoelki** [comment]
hey there, thanks for the contribution!

in general, the whole purpose was to have no emojis at all if you just select `none`. so this behaviour is correct.

**Comment by quanru** [comment]
Sorry, I thought 'none' was the default

**Comment by quanru** [comment]
I found that "none" is indeed the default value. If it is normal for emojis not to be displayed when "none" is selected, then setting the default value to "native" would be better, right?

**Comment by quanru** [comment]
@FlorianWoelki Please have a look!

**Comment by FlorianWoelki** [comment]
thank you for your contribution!

**Review by FlorianWoelki — APPROVED** [review]

**Pull request merged**
